package:
  name: zc.buildout
  version: !!str 2.5.0

source:
  fn: zc.buildout-2.5.0.tar.gz
  url: https://pypi.python.org/packages/source/z/zc.buildout/zc.buildout-2.5.0.tar.gz
  md5: 4c31eb4fae176b15e1e1e7dbaba159be
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - zc.buildout = zc.buildout:main
    #
    # Would create an entry point called zc.buildout that calls zc.buildout.main()

    - buildout=zc.buildout.buildout:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - zc.buildout
    - zc

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - buildout --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://buildout.org
  license: Zope Public License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
